#!/usr/bin/env python3
"""
LLM Integration Comparison Demo.

This script demonstrates the difference between pre-defined responses
and real LLM-generated responses in the Tachikoma system.
"""

import asyncio
import sys
import os

# Add the tachikoma package to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'tachikoma'))

from tachikoma.simple.agent import SimpleAgent, AgentRole, PersonalityType
from tachikoma.simple.orchestrator import SimpleOrchestrator
from tachikoma.simple.llm_integration import MockLLMProvider, OpenAIProvider, LLMOrchestrator


def create_test_team():
    """Create a test team for comparison."""
    
    legal_agent = SimpleAgent(
        name="Alice",
        role=AgentRole.LEGAL,
        personality=PersonalityType.ANALYTICAL,
        expertise=["Corporate Law", "Compliance", "Risk Assessment"],
        performance_score=0.85
    )
    
    marketing_agent = SimpleAgent(
        name="Bob",
        role=AgentRole.MARKETING,
        personality=PersonalityType.CREATIVE,
        expertise=["Digital Marketing", "Brand Strategy", "Market Research"],
        performance_score=0.78
    )
    
    tech_agent = SimpleAgent(
        name="Charlie",
        role=AgentRole.TECHNICAL,
        personality=PersonalityType.PRACTICAL,
        expertise=["System Architecture", "Software Development", "Cloud Computing"],
        performance_score=0.92
    )
    
    return [legal_agent, marketing_agent, tech_agent]


async def demonstrate_predefined_vs_llm():
    """Demonstrate the difference between predefined and LLM responses."""
    
    print("Tachikoma LLM Integration Comparison Demo")
    print("=" * 60)
    print("This demo shows the difference between:")
    print("1. Pre-defined template responses (current Phase 1)")
    print("2. LLM-generated dynamic responses")
    print("=" * 60)
    
    # Create test team
    agents = create_test_team()
    
    # Test scenario
    scenario = "Should we invest in AI technology for customer service automation?"
    
    print(f"\n[SCENARIO] {scenario}")
    
    # ========================================
    # PART 1: PRE-DEFINED RESPONSES
    # ========================================
    print("\n" + "="*60)
    print("PART 1: PRE-DEFINED TEMPLATE RESPONSES")
    print("="*60)
    print("(Current Phase 1 system - hardcoded templates)")
    
    orchestrator = SimpleOrchestrator()
    for agent in agents:
        orchestrator.add_agent(agent)
    
    print("\n[PRE-DEFINED] Agent responses:")
    for agent in agents:
        response = orchestrator.simulate_agent_interaction(agent.name, scenario)
        print(f"\n{agent.name} ({agent.role.value}):")
        print(f"  {response}")
        print(f"  [Note: This is a hardcoded template based on role and keywords]")
    
    # ========================================
    # PART 2: MOCK LLM RESPONSES
    # ========================================
    print("\n" + "="*60)
    print("PART 2: MOCK LLM RESPONSES")
    print("="*60)
    print("(Using mock LLM provider - simulates real LLM behavior)")
    
    mock_llm = MockLLMProvider()
    llm_orchestrator = LLMOrchestrator(mock_llm)
    
    for agent in agents:
        llm_orchestrator.add_agent(agent)
    
    print("\n[MOCK LLM] Agent responses:")
    for agent in agents:
        response = await llm_orchestrator.generate_dynamic_response(agent.name, scenario)
        print(f"\n{agent.name} ({agent.role.value}):")
        print(f"  {response}")
        print(f"  [Note: This is generated by mock LLM based on agent characteristics]")
    
    # ========================================
    # PART 3: CONVERSATION SIMULATION
    # ========================================
    print("\n" + "="*60)
    print("PART 3: LLM CONVERSATION SIMULATION")
    print("="*60)
    print("(Multi-turn conversation using LLM-generated responses)")
    
    print("\n[LLM CONVERSATION] Running multi-turn conversation...")
    conversation_results = await llm_orchestrator.run_llm_conversation(scenario, max_turns=4)
    
    print(f"\n[CONVERSATION RESULTS]")
    print(f"  Scenario: {conversation_results['scenario']}")
    print(f"  Total Turns: {len(conversation_results['turns'])}")
    print(f"  Agents Participated: {len(set(turn['agent'] for turn in conversation_results['turns']))}")
    
    # ========================================
    # PART 4: REAL LLM INTEGRATION (Optional)
    # ========================================
    print("\n" + "="*60)
    print("PART 4: REAL LLM INTEGRATION")
    print("="*60)
    print("(Uncomment and configure to use real OpenAI API)")
    
    # Uncomment the following lines to use real OpenAI API
    # You'll need to set your OpenAI API key
    """
    try:
        # Replace with your actual OpenAI API key
        openai_key = "your-openai-api-key-here"
        openai_llm = OpenAIProvider(openai_key, model="gpt-3.5-turbo")
        openai_orchestrator = LLMOrchestrator(openai_llm)
        
        for agent in agents:
            openai_orchestrator.add_agent(agent)
        
        print("\n[REAL LLM] Agent responses using OpenAI:")
        for agent in agents:
            response = await openai_orchestrator.generate_dynamic_response(agent.name, scenario)
            print(f"\n{agent.name} ({agent.role.value}):")
            print(f"  {response}")
            print(f"  [Note: This is generated by real OpenAI GPT model]")
            
    except Exception as e:
        print(f"  [Error: {e}]")
        print("  [Note: Configure OpenAI API key to test real LLM integration]")
    """
    
    print("\n[INFO] To use real LLM integration:")
    print("  1. Install OpenAI: pip install openai")
    print("  2. Set your API key in the code")
    print("  3. Uncomment the real LLM section above")
    
    # ========================================
    # COMPARISON SUMMARY
    # ========================================
    print("\n" + "="*60)
    print("COMPARISON SUMMARY")
    print("="*60)
    
    print("\n[PRE-DEFINED RESPONSES]")
    print("  + Fast and predictable")
    print("  + No API costs")
    print("  + Works offline")
    print("  - Limited variety")
    print("  - Not contextually aware")
    print("  - Feels robotic")
    
    print("\n[LLM-GENERATED RESPONSES]")
    print("  + Dynamic and varied")
    print("  + Contextually aware")
    print("  + More natural conversation")
    print("  + Can adapt to different scenarios")
    print("  - Requires API calls")
    print("  - May have costs")
    print("  - Requires internet connection")
    
    print("\n[RECOMMENDATION]")
    print("  Phase 1: Use pre-defined responses for testing core architecture")
    print("  Phase 2: Add LLM integration for dynamic conversations")
    print("  Phase 3: Implement hybrid approach (templates + LLM)")
    
    print("\n" + "="*60)
    print("LLM COMPARISON DEMO COMPLETED!")
    print("="*60)


if __name__ == "__main__":
    asyncio.run(demonstrate_predefined_vs_llm())
